/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'junho85' at '11/15/15 1:20 PM' with Gradle 2.8
 *
 * @author junho85, @date 11/15/15 1:20 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
